package arreglos;

public class Arreglo1 {

	public static void main(String[]args)
	{
		
	
	//TODO Autogenerated method stub
	  int numero;
	  numero=5;
	  numero=1999;
	  numero=-234;
	  numero=numero+1000;
	  
	  //ARRAY - Arreglos
	  //VECTOR - Vector
	  //MATRIX	- Matriz
	  
	  int numeros[]= new int[10];
	  
	  char palabra[]= new char[8];
	  
	  numeros[1]=20;
	  numeros[3]=20;
	  
	  
	  numeros[9]= numeros[1]*numeros[3];
	  
	  char[] palabras = new char[] {'a','b','c','d'};
	  
	
	}
	
}
